import React, { useCallback, useEffect, useRef, useState } from "react";
import { useParams } from "react-router-dom";
import { AlertCircle, Bot, CheckCircle2, Clock, Loader2, Mic, MicOff, Volume2 } from "lucide-react";
import { answerAIInterview, completeAIInterview, getAIInterviewSession, startAIInterview } from "../../api/recruitment.api";

const PRIMARY = "#0E7C86";
const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition;
const voiceSupported = Boolean(Recognition && window.speechSynthesis);
const button = { background: PRIMARY, color: "white", border: "none", borderRadius: 9, padding: "12px 18px", fontWeight: 700, cursor: "pointer" };
const textButton = { background: "transparent", border: "none", color: PRIMARY, padding: 0, cursor: "pointer", display: "inline-flex", gap: 6, alignItems: "center", fontWeight: 600 };
const time = s => `${String(Math.floor(Math.max(0, s) / 60)).padStart(2, "0")}:${String(Math.max(0, s) % 60).padStart(2, "0")}`;

function say(text, done) { window.speechSynthesis?.cancel(); if (!window.speechSynthesis) return; const u = new SpeechSynthesisUtterance(text); u.rate = .95; u.onend = done; window.speechSynthesis.speak(u); }

export default function TakeInterview() {
  const { token } = useParams();
  const [screen, setScreen] = useState("loading"), [session, setSession] = useState(null), [question, setQuestion] = useState(null), [answer, setAnswer] = useState(""), [voice, setVoice] = useState(false), [listening, setListening] = useState(false), [speaking, setSpeaking] = useState(false), [remaining, setRemaining] = useState(0), [error, setError] = useState("");
  const recognition = useRef(null), answerRef = useRef("");
  const stopMedia = useCallback(() => { try { recognition.current?.stop(); } catch (_) {} recognition.current = null; setListening(false); window.speechSynthesis?.cancel(); setSpeaking(false); }, []);
  useEffect(() => { getAIInterviewSession(token).then(data => { setSession(data); setRemaining(data.remainingSeconds || data.durationSeconds || 0); setScreen("intro"); }).catch(e => { setError(e?.response?.data?.message || "This interview link is invalid or expired."); setScreen("error"); }); return stopMedia; }, [token, stopMedia]);
  useEffect(() => { if (!session?.expiresAt || screen !== "interview") return undefined; const tick = () => { const left = Math.max(0, Math.ceil((new Date(session.expiresAt) - Date.now()) / 1000)); setRemaining(left); if (!left) { stopMedia(); completeAIInterview(token).catch(() => {}); setScreen("done"); } }; tick(); const id = setInterval(tick, 1000); return () => clearInterval(id); }, [session?.expiresAt, screen, stopMedia, token]);
  useEffect(() => { if (screen === "interview" && voice && question) { setSpeaking(true); say(question.question, () => setSpeaking(false)); } }, [question, screen, voice]);
  async function start(useVoice) { try { setScreen("working"); setVoice(useVoice); const data = await startAIInterview(token); setQuestion(data.question); setRemaining(data.remainingSeconds); setSession(s => ({ ...s, expiresAt: data.expiresAt })); setScreen("interview"); } catch (e) { setError(e?.response?.data?.message || "Unable to start interview."); setScreen("error"); } }
  function toggleMic() { if (listening) return stopMedia(); window.speechSynthesis?.cancel(); const r = new Recognition(); r.lang = "en-US"; r.continuous = true; r.interimResults = true; r.onresult = e => { let add = ""; for (let i = e.resultIndex; i < e.results.length; i += 1) if (e.results[i].isFinal) add += ` ${e.results[i][0].transcript}`; if (add) { answerRef.current = `${answerRef.current} ${add}`.trim(); setAnswer(answerRef.current); } }; r.onend = () => setListening(false); r.onerror = () => setListening(false); recognition.current = r; r.start(); setListening(true); }
  async function submit() { if (!answer.trim()) return; stopMedia(); setScreen("working"); try { const data = await answerAIInterview(token, answer.trim()); if (data.complete) return setScreen("done"); answerRef.current = ""; setAnswer(""); setQuestion(data.question); setRemaining(data.remainingSeconds); setSession(s => ({ ...s, expiresAt: data.expiresAt })); setScreen("interview"); } catch (e) { setError(e?.response?.data?.message || "Your answer could not be saved."); setScreen("error"); } }
  async function finish() { stopMedia(); setScreen("working"); try { await completeAIInterview(token); setScreen("done"); } catch (e) { setError(e?.response?.data?.message || "Unable to complete interview."); setScreen("error"); } }
  const Shell = ({ children }) => <main style={{ minHeight: "100vh", background: "#f7fafc", fontFamily: "Inter, sans-serif", color: "#172033" }}><header style={{ padding: "16px 6vw", background: "white", borderBottom: "1px solid #dce8ea", display: "flex", gap: 10, alignItems: "center" }}><Bot color={PRIMARY}/><strong>HRMS AI Interview</strong></header><section style={{ maxWidth: 720, margin: "0 auto", padding: "48px 20px" }}>{children}</section></main>;
  if (screen === "loading" || screen === "working") return <Shell><div style={{ textAlign: "center", padding: 70 }}><Loader2 color={PRIMARY} style={{ animation: "spin 1s linear infinite" }} size={38}/><p>{screen === "working" ? "The interviewer is considering the next step…" : "Loading interview…"}</p></div></Shell>;
  if (screen === "error") return <Shell><div style={{ textAlign: "center" }}><AlertCircle color="#dc2626" size={48}/><h1>Interview unavailable</h1><p>{error}</p></div></Shell>;
  if (screen === "done") return <Shell><div style={{ textAlign: "center", padding: 45 }}><CheckCircle2 color="#059669" size={62}/><h1>Interview complete</h1><p>Thank you for your time. Your responses have been securely recorded for the recruitment team.</p></div></Shell>;
  if (screen === "intro") return <Shell><article style={{ background: "white", border: "1px solid #dce8ea", borderRadius: 16, padding: 30 }}><Bot size={42} color={PRIMARY}/><h1>Welcome, {session?.candidateName}</h1><p>You'll interview for <strong>{session?.jobTitle}</strong>. The interviewer chooses each next question from your answers, experience, and role requirements.</p><p><Clock size={16} style={{ verticalAlign: "middle" }}/> You have {Math.round((session?.durationSeconds || 0) / 60)} minutes once you begin. The server controls the timer.</p><p>Answer one question at a time. The interview may finish early when enough job-relevant evidence is collected.</p><button onClick={() => start(false)} style={button}>Begin interview</button>{voiceSupported && <button onClick={() => start(true)} style={{ ...button, background: "white", color: PRIMARY, border: `1px solid ${PRIMARY}`, marginLeft: 10 }}>Begin with voice</button>}</article></Shell>;
  return <Shell><div style={{ display: "flex", justifyContent: "space-between", marginBottom: 18, color: PRIMARY, fontWeight: 700 }}><span>{question?.type || "Interview question"}</span><span><Clock size={15} style={{ verticalAlign: "middle" }}/> {time(remaining)}</span></div><article style={{ background: "white", border: "1px solid #dce8ea", borderRadius: 16, padding: 30 }}><div style={{ fontSize: 12, textTransform: "uppercase", color: "#64748b" }}>{question?.topic || question?.skill || "AI interviewer"} · {question?.difficulty || "calibrated"}</div><h1 style={{ fontSize: 22, lineHeight: 1.45 }}>{question?.question}</h1>{voice && <button onClick={() => { setSpeaking(true); say(question.question, () => setSpeaking(false)); }} style={textButton}><Volume2 size={17}/> {speaking ? "Speaking…" : "Replay question"}</button>}<textarea value={answer} onChange={e => { answerRef.current = e.target.value; setAnswer(e.target.value); }} rows={7} placeholder="Speak or type your answer…" style={{ width: "100%", boxSizing: "border-box", marginTop: 18, padding: 14, borderRadius: 10, border: "1px solid #b7cdd0", font: "inherit", lineHeight: 1.5 }}/>{voice && <button onClick={toggleMic} style={{ ...textButton, color: listening ? "#dc2626" : PRIMARY, marginTop: 10 }}>{listening ? <MicOff size={17}/> : <Mic size={17}/>} {listening ? "Stop recording" : "Record answer"}</button>}<div style={{ display: "flex", justifyContent: "space-between", marginTop: 22 }}><button onClick={finish} style={textButton}>Finish interview</button><button onClick={submit} disabled={!answer.trim()} style={{ ...button, opacity: answer.trim() ? 1 : .5 }}>Submit answer</button></div></article></Shell>;
}
