export const STEPS = [
  { id: 0, label: "Personal Info" },
  { id: 1, label: "Employment" },
  { id: 2, label: "Compensation" },
  { id: 3, label: "Bank" },
  { id: 4, label: "Review" },
];

export const INITIAL_VALUES = {
  employee_id: "",
  biometric_id: "",
  first_name: "",
  last_name: "",
  email: "",
  mobile: "",
  department_id: "",
  emp_job_title: "",
  reporting_to: "none",
  emp_joining_date: "",
  date_of_confirmation: "",
  contract_end_date: "",
  employee_type: "Full-Time",
  project_cost_centre: "",
  previous_designation: "",
  previous_employer: "",
  total_exp_before_joining: "",
  bgv_status: "",
  assigned_member: "",
  ctc: "",
  benefits_plan: "standard",
  role: "2",

  gender: "",
  dob: "",
  actual_dob: "",
  marital_status: "",
  father_name: "",
  spouse_name: "",
  aadhaar_number: "",
  aadhaar_name: "",
  aadhaar_enrolment_number: "",
  pan_number: "",
  uan_number: "",
  educational_qualification: "",
  access_card_number: "",
  access_card_from_date: "",
  access_card_to_date: "",
  pf_number: "",
  pf_join_date: "",
  esi_number: "",

  bank_name: "",
  account_number: "",
  account_type: "",
  bank_branch: "",
  dd_payable_at: "",
  ifsc_code: "",
  account_holder_name: "",
  payment_type: "",

  contact_name: "",
  contact_city: "",
  contact_country: "",
  personal_email: "",
  alternate_mobile: "",
  emergency_contact_name: "",
  emergency_contact_phone: "",
  permanent_address_line1: "",
  permanent_address_line2: "",
  permanent_address_line3: "",
};
